
GO

/****** Object:  Table [dbo].[PlanType]    Script Date: 03-01-2020 15:24:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PlanType](
	[PlanTypeId] [int] IDENTITY(1,1) NOT NULL,
	[PlanTypeName] [varchar](max) NULL,
	[StatusFlag] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PlanTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PlanType] ADD  DEFAULT ((1)) FOR [StatusFlag]
GO


